### ISSUE TITLE
SortedDict Simple Way to Get Key from Bisect

### ISSUE THREAD

**Issue by RoyLarson** [grantjenks/python-sortedcontainers#103]
I am trying to retrieve the key that is less than or greater than an input key.

``
    
    from sortedcontainers import SortedDict
    import datetime
    today = datetime.date.today()
    test = SortedDict({today: 'Value'})

    tomorrow = today + datetime.timedelta(days=1)
    left = test.bisect_left(tomorrow)
    assert left == today 

Left returns 0 in this case which is not the key but the index to the key list
The other option I thought was 

    left = test.bisect_key_left(tomorrow)

But then I get: AttributeError: 'SortedDict' object has no attribute 'bisect_key_left'

Is there a way to return left or right key (depending on the bisect_left/bisect_right call)?

**Comment by grantjenks** [comment]
I think you want `SortedDict.irange` http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedcontainers.SortedList.irange instead.

See also this answer: https://stackoverflow.com/a/22997000/

**Comment by RoyLarson** [comment]
I am thinking something more like this
``    

    def left_key(sd, value):
        left_id = sd.bisect_left(value)
        if value in sd:
            return value
        else:
            try:
                return sd.keys()[left_id]
            except IndexError:
                if sd.keys()[-1] < value:
                    return sd.keys()[-1]
                else:
                    raise ValueError('No Value Smaller Than {}'.format(value))


    def right_key(sd, value):
        right_id = sd.biscet_right(value)
        try:
            right_key = sd.keys()[right_id]
        except IndexError:
            raise ValueError('No Value Larger Than {}'.format(value))

        return right_key

I think this would be correct but will put together some tests to try to flesh out the corner cases

**Comment by grantjenks** [comment]
I’m willing to consider a pull request.
