### ISSUE TITLE
SortedList key using two values

### ISSUE THREAD

**Issue by nengine** [grantjenks/python-sortedcontainers#108]
```py
orders = [
{'price': 1.0, 'time':  100},
{'price': 1.0, 'time':  200},
{'price': 2.0, 'time':  100},
{'price': 2.0, 'time':  200},
]

ascending = SortedList(orders, key = lambda order: -order.price)
decending = SortedList(orders, key = lambda order: order.price)

```
I wanted to use SortedList to sort by price and unix timestamp basically using two values for key.  Please let me know if this is possible?  Possibly I could combine price and timestamp as a single key, but with different data types, it becomes quite messy.  Would be nice if I can define 1st key, 2nd key, etc.

Thank you.

**Comment by grantjenks** [comment]
Try returning a tuple of two elements: (price, timestamp) from the key function. Tuples use lexicographic ordering so the first element is compared and if that is equal then the second argument is compared. Something like: key=lambda order: (order.price, order.timestamp)

**Comment by nengine** [comment]
Wow! Thank you. (order.price, order.timestamp) turple works on SortedList.   I just also realized about SortedDict and could use order.price as key and SortedList to store list of orders sorted by order.time key as value.

**Comment by nengine** [comment]
Hello, Would you know if there is javascript implementation SortedDict and SortedList?  Thanks.

**Comment by grantjenks** [comment]
I don’t know.
