### ISSUE TITLE
Make objects re-sort themselves when in the list

### ISSUE THREAD

**Issue by naiveai** [grantjenks/python-sortedcontainers#109]
With this minimal example:

```python3
import functools
from sortedcontainers import SortedList

@functools.total_ordering
class Point:
	def __init__(self, x, y):
		self.x, self.y = x, y

	def __eq__(self, other):
        return (self.x == other.x) and (self.y == other.y)

    def __lt__(self, other):
        return (self.x < other.x) or (self.y < other.y)

k = SortedList([Point(3, 4), Point(1, 2)])
```

We can see:

```python3
>>> k
# This is correct, but then...
SortedList([Point(x=1, y=2), Point(x=3, y=4)])
>>> k[0].x == 4
>>> k
SortedLIst([Point(x=4, y=2), Point(x=3, y=4)])
```

I'm pretty sure this is intended behavior, but it seems confusing to me. Is it worth resorting the list when an object is modified?

**Comment by naiveai** [comment]
I have now realized I utterly foolish this is in almost every way, my sincerest apologies.

**Comment by grantjenks** [comment]
No problem. Comes up quite often.

There’s a write up in the docs under caveats at: http://www.grantjenks.com/docs/sortedcontainers/introduction.html#caveats
