### ISSUE TITLE
Problem with SortedDict using a key-function

### ISSUE THREAD

**Issue by AndyW118** [grantjenks/python-sortedcontainers#111]
I am trying to use SortedDict with a key function in order to have a case-insensitive sorted dictionary. Here is my code:

import sortedcontainers as sc

def keyfunction(key):
    return key.lower()

d = sc.SortedDict(keyfunction)

d['xyz'] = 1
d['ABC'] = 2

try:
    r = d['xYZ']
except Exception as e:
    print(str(e))

The key-function is entered each time I add an item to the dictionary.  But it isn't called when I try to retrieve a previously entered item ('xyz') using 'xYZ' instead.  Shouldn't it be?  Am I doing something wrong?  If so, is there a way to get the functionality I want?  Thanks.  (I am new to Python, so I may well be doing something stupid.)

**Comment by grantjenks** [comment]
The key-function affects only the sort order of the dictionary's keys. It doesn't change the hashing of the keys at all. The following is expected behavior:

```
In [1]: import sortedcontainers as sc

In [2]: sd = sc.SortedDict(str.lower)

In [3]: sd['abc'] = 0

In [4]: sd['Abc'] = 1

In [5]: sd['aBc'] = 2

In [6]: sd['abC'] = 3

In [7]: sd
Out[7]: SortedDict(<method 'lower' of 'str' objects>, {'abc': 0, 'Abc': 1, 'aBc': 2, 'abC': 3})
```
