### ISSUE TITLE
Provide __reduce__ for more robust pickling

### ISSUE THREAD

**Issue by hniksic** [grantjenks/python-sortedcontainers#112]
It seems that `SortedList` doesn't implement support for pickling except by inheriting `object.__reduce__`. The pickle output therefore contains field that are implementation details of the class.

Consider the result of calling `__reduce__()` on `SortedList([1, 2, 3])`:

```py
>>> sortedcontainers.SortedList((1, 3, 2)).__reduce__()
(<function _reconstructor at 0x7f566564c268>, (<class 'sortedcontainers.sortedlist.SortedList'>, <class 'object'>, None), {'_len': 3, '_lists': [[1, 2, 3]], '_maxes': [3], '_index': [], '_load': 1000, '_twice': 2000, '_half': 500, '_offset': 0})
```

Pickling and unpickling presently works with this implementation, but this approach has two issues:

* it is not optimal wrt space, since it includes unnecessary data. Ideally it would only pickle the sequence of 1, 2, 3, and the fact that it's stored in a `SortedList`. The `__reduce__` protocol is [designed](https://docs.python.org/3/library/pickle.html#object.__reduce__) with such usage in mind.
* it leaks private fields, which are clearly implementation details, into the peristent format. Even a slight change in the implementation would likely cause unpickling to fail.

An implementation that resolves both issues might look like this, in the case of `SortedList`:

```py
    def __reduce__(self):
        return type(self), (), None, iter(self)
```

Here is a small comparison of the two:

```py
class X(sortedcontainers.SortedList):
    def __reduce__(self):
        return type(self), (), None, iter(self)

class Y(sortedcontainers.SortedList):
  pass

>>> x, y = X([1, 2, 3]), Y([1, 2, 3])
>>> x.__reduce__()
(<class '__main__.X'>, (), None, <itertools.chain object at 0x7f5665d444a8>)
>>> pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
b'\x80\x04\x95\x1d\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x01X\x94\x93\x94)R\x94(K\x01K\x02K\x03e.'
>>> pickle.loads(_)
X([1, 2, 3], load=1000)
>>> pickle.dumps(y, protocol=pickle.HIGHEST_PROTOCOL)
b'\x80\x04\x95\x80\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x01Y\x94\x93\x94)\x81\x94}\x94(\x8c\x04_len\x94K\x03\x8c\x06_lists\x94]\x94]\x94(K\x01K\x02K\x03ea\x8c\x06_maxes\x94]\x94K\x03a\x8c\x06_index\x94]\x94\x8c\x05_load\x94M\xe8\x03\x8c\x06_twice\x94M\xd0\x07\x8c\x05_half\x94M\xf4\x01\x8c\x07_offset\x94K\x00ub.'
>>> pickle.loads(_)
Y([1, 2, 3], load=1000)
```

**Comment by grantjenks** [comment]
Yes, that’s a very reasonable improvement. 

Note that SortedDict and SortedSet define their own reduce method too. You might want to look at those.

**Comment by tamirOK** [comment]
@grantjenks Is this issue is already solved?

**Comment by grantjenks** [comment]
Yes, it's been merged to master but not yet released.

Come to think of it, I wonder if this is a breaking change. I didn't take any precautions for backwards compatibility.

**Comment by skettlitz** [comment]
> Come to think of it, I wonder if this is a breaking change. I didn't take any precautions for backwards compatibility.

It seems that it indeed is a breaking change and unpickling of old data is not possible with the current version included in winpython. I just tried to unpickle a sorteddict that was pickled with an older version and it threw an exception.

> TypeError: update expected at most 1 arguments, got 2
in 
> ...sorteddict.py", line 548, in update
> self._dict_update(*args, **kwargs)

The workaround for me now is to use an older version of sortedcontainers.

**Comment by grantjenks** [comment]
Are you installing from PyPI or Github? I think I pushed these changes to master but did not release a new version.

**Comment by skettlitz** [comment]
I'm using Winpython and am not quite sure which source was used.

The "broken" new version was either with Winpython 3.7.1 or installed/updated with pip and the version is:
> __version__ = '2.1.0'

The "working" old version was either supplied with Winpython 3.6.3 or was installed/updated with pip and the version is:
> __version__ = '1.5.7'

**Comment by skettlitz** [comment]
The problems with unpickling old data I see are for sorteddict which is probably different from sortedlist which is the main topic of this issue. Should we open a new issue for sorteddict?

**Comment by grantjenks** [comment]
Yes, please open a separate issue with steps to reproduce.

**Comment by grantjenks** [comment]
I don't intend to support pickling across major versions of sortedcontainers.

The original pickling that inherited ``object.__reduce__`` relies too heavily on object internals. And the newer ``__reduce__`` methods make this easier but I still think it's a difficult feature to support long-term.

The testing that this feature would generally require means pickling/unpickling across all versions which is onerous. I would advise converting SortedList to list, SortedDict to dict, and SortedSet to set and then serializing those representations with whatever protocol you prefer.
