### ISSUE TITLE
__getitem__ optimization for small slices

### ISSUE THREAD

**Issue by belm0** [grantjenks/python-sortedcontainers#117]
use case:  e.g. need to access an index and its neighboring nodes (slice length of 3)

I noticed that `__getitem__` calls `_pos()` twice and then shortcuts if start_pos == stop_pos.  Rather it could check for start_pos list length > start_idx + slice_length, and elide the second `_pos()` call.

https://github.com/grantjenks/python-sortedcontainers/blob/d127cdde5f77804fe51f355fdad469a0ac7caede/sortedcontainers/sortedlist.py#L843-L853

**Comment by grantjenks** [comment]
Good idea! Would you create a pull request?

**Comment by belm0** [comment]
I'll make an attempt and try to confirm with timeit data.

Beyond that I'm wondering if a single `_pos()` call could be simpler and faster in all cases of step 1.  I'll take a stab.
