### ISSUE TITLE
Canonical ordering on sets

### ISSUE THREAD

**Issue by dirkroorda** [grantjenks/python-sortedcontainers#120]
Not so much an issue as an observation: if the element type of a class of sets is totally ordered, then the sets themselves can be totally ordered in a very natural way.

Suppose we have sets of integers.

Then A < B if and only if the least element of A or B that is not contained in the other, is contained in A.

This ordering coincides with the tree ordering if the class of sets forms a tree. 

In fact, this ordering is a natural generalization of the tree ordering to arbitrary graphs.

**Comment by grantjenks** [comment]
I guess that's true. Did this stand out because of the Caveats section of the Introduction in the docs? I'm not sure that caveat-caveat is worth explaining ;)

**Comment by dirkroorda** [comment]
I'm working with a model for texts which consists of a graph of nodes and edges.
The nodes are integers that correspond with the position of a word in the total stream.
You can define complex textual objects as sets of nodes.

When you work with a tree like model of text, there is a nice ordering of complex textual objects, based on embedding and sequence. Basically: bigger objects come before embedded smaller objects, earlier objects come before later objects. This is a total ordering.

But in general, texts are not trees, and if we generalise to graphs in general, we loose this nice total ordering. Until you replace it with the *canonical* ordering as described above.

I agree with you that at the level of genericity of your module, it would be beyond the mark to explain this all.

But it does remain a nice, generic subcase of a total ordering on sets with an element type that can be totally ordered.
