### ISSUE TITLE
Function call overhead

### ISSUE THREAD

**Issue by dirkroorda** [grantjenks/python-sortedcontainers#121]
Despite how nicely done SortedSet is, it still suffers from function-call overhead.
https://ilovesymposia.com/2015/12/10/the-cost-of-a-python-function-call/

I tested `i in s` versus `i in ss` with `s` an ordinary set, and `ss` a `SortedSet`.

```python
ss = SortedSet(i * 10 for i in range(1000000))
s = set(i * 10 for i in range(1000000))

def isin():
  n = 0
  for i in range(100000):
    if i * 2 in s:
      n += 1
  return n

def issin():
  cnts = ss.__contains__
  n = 0
  for i in range(100000):
    if cnts(i * 2):
      n += 1
  return n
```

The resulting performance is this

## isin()

```
 2 function calls in 0.012 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.012    0.012    0.012    0.012 <ipython-input-6-8e16a711c68a>:1(isin)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

```

## issin()

```
         100002 function calls in 0.037 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.024    0.024    0.037    0.037 <ipython-input-41-f46da62b1c24>:1(issin)
   100000    0.014    0.000    0.014    0.000 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sortedcontainers/sortedset.py:194(__contains__)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

```

There is a 3 x slowdown spent in just calling the function `__contains__` (not executing it).
If I did not localize the `__contains__` function into `cnts`, but had just said `i * 2 in ss` the slowdown is even worse (3.5 x).

So I think this module would benefit greatly by a C extension.

With this factor 3 of slowdown, I doubt whether I can get the performance gain I wanted to achieve by replacing sets by SortedSets. The thing is, I need `irange`, but I still do need a lot if set containment tests.

**Comment by dirkroorda** [comment]
I am now tempted to keep an ordinary set with the same elements next to the SortedSet copy. As I use the sets without modifying them, this is not too bad. Only a waste of RAM.
The alternative is to peel the code for SortedSet apart, so that I can do `irange` and `in` on just a set and a list.

**Comment by grantjenks** [comment]
Sorted Set keeps a set already. Just grab a reference to it. The attribute is sorted_set._set

For better performance, cythonize all of it and you’ll get the interpreter overhead out of the way.

**Comment by dirkroorda** [comment]
Thanks for the hint of grabbing the reference to the existing set, good idea!
I am very tempted to use Cython as well, because a lot of my data are just integers.
The thing that keeps me from it is that I do not see a workable way to distribute my module to Mac and Windows users without C-compilers.

**Comment by dirkroorda** [comment]
```python
def issin2():
  s = ss._set
  n = 0
  for i in range(100000):
    if i * 2 in s:
      n += 1
  return n
```

## issin2
Lo and behold!

```
  2 function calls in 0.010 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.010    0.010    0.010    0.010 <ipython-input-58-1b12ec682e8a>:1(issin2)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

This is the way forward! Thanks again!

**Comment by AndreiPashkin** [comment]
> The thing that keeps me from it is that I do not see a workable way to distribute my module to Mac and Windows users without C-compilers.

Packages with pre-compiled libraries could solve this.
