### ISSUE TITLE
Version 2.1.0 can't unpickle sorteddict from version 1.5.7

### ISSUE THREAD

**Issue by skettlitz** [grantjenks/python-sortedcontainers#122]
When I try to unpickle data that was pickled with an older version and an exception is being thrown. Unpickling data with the same version is working as expected.

**Steps to reproduce:**

On old installation with version 1.5.7 pickle a sorteddict:
```
import pickle
import sortedcontainers
sortedcontainers.__version__
```
**'1.5.7'**
```
pickle.dumps(sortedcontainers.sorteddict.SortedDict({123:'test'}))
```
**b'\x80\x03csortedcontainers.sorteddict\nSortedDict\nq\x00NM\xe8\x03]q\x01K{X\x04\x00\x00\x00testq\x02\x86q\x03a\x87q\x04Rq\x05.'**
```
pickle.loads(b'\x80\x03csortedcontainers.sorteddict\nSortedDict\nq\x00NM\xe8\x03]q\x01K{X\x04\x00\x00\x00testq\x02\x86q\x03a\x87q\x04Rq\x05.')
```
Works as expected and returns: **SortedDict(None, 1000, {123: 'test'})**

On new installation with version 2.1.0 try to unpickle.
```
import pickle
import sortedcontainers
sortedcontainers.__version__
```
**'2.1.0'**
```
pickle.loads(b'\x80\x03csortedcontainers.sorteddict\nSortedDict\nq\x00NM\xe8\x03]q\x01K{X\x04\x00\x00\x00testq\x02\x86q\x03a\x87q\x04Rq\x05.')
```
Throws exception: **TypeError: update expected at most 1 arguments, got 2**

**Suspected cause:**
Differences in the __reduce__ function and corresponding changes in the data handling on loading.
reduce in 1.5.7: **return (self.class, (self._key, self._load, list(self._iteritems())))**
reduce in 2.1.0: **return (self.class, (self._key, list(self.items())))**

**Comment by grantjenks** [comment]
I am tempted to close this as “won’t fix” simply because it’s something I never intended to guarantee. Is there a solution that doesn’t require changing the init method? I wonder how many others expect serialization to continue working across major version changes.

**Comment by skettlitz** [comment]
It caught me by surprise since you can generally unpickle basic data structures from python 2 in python 3 (and vice versa in most cases).

If not fixed I would wish for:

* an assertion triggered by the bad data which throws a proper error message like "obsolete data format detected".

* a method to convert the old data to the new version.

**Comment by grantjenks** [comment]
The issue here is not Python 2 vs Python 3 but rather v1 of sortedcontainers vs v2. If Python 3 is used with v1 of sortedcontainers then the deserialization will work.

I would prefer not to support pickling across major versions of sortedcontainers. Pickling is supported for identical versions but nothing more.
