### ISSUE TITLE
This forces entries of SortedSet to be hash-able. Collections in other languages like Java or C# don't have such limitations.

### ISSUE THREAD

**Issue by sergeyDoroshenko** [grantjenks/python-sortedcontainers#125]
https://github.com/grantjenks/python-sortedcontainers/blob/626ed57d21bfbe36c6581b6691fccf9e5a7cba8c/sortedcontainers/sortedset.py#L357

**Comment by grantjenks** [comment]
Yes, that is true. SortedSet is not like a TreeSet. It's intentional as it supports many optimizations and greatly simplifies the implementation. Typically, if you can define a total order for sorting then you can also define a hash function.
