### ISSUE TITLE
SortedDict cooperative inheritance

### ISSUE THREAD

**Issue by alkasm** [grantjenks/python-sortedcontainers#126]
I attempted to create a sorted `defaultdict` via the usual subclassing/dependency injection means:

```python
class SortedDefaultDict(SortedDict, defaultdict):
    pass
```

This doesn't work though, because the `SortedDict` initializer doesn't actually call the superclass's initializer. The important bits of the initializer for this discussion is:

```python
def __init__(self, *args, **kwargs):
    ...
    if args and (args[0] is None or callable(args[0])):
        _key = self._key = args[0]
        args = args[1:]
    else:
        _key = self._key = None
    ...
    self._update(*args, **kwargs)
```

Basically, even though `SortedDict` inherits from `dict`, it ends up just assuming that the calling convention to whatever subclass used will be the same calling convention as `dict.update()`, passing an iterable of (k, v) pairs or kwargs to the `update()` method of the superclass, instead of initializing the superclass with those values.

I don't think there's any magic bullet here in terms of an easy solution to properly subclass for user extensibility without changing your calling convention and thus your API. 

There are solutions of course from a users point of view. Raymond Hettinger has some good suggestions in his [super() considered super!][hettinger] blogpost. Either way, it may be nice to provide this functionality to users without extra work on their end if it's possible without totally flipping the API (e.g. requiring key functions to be passed via `kwargs`, which inherently means that you cannot use that as a key in your dictionary, or even passing in the initial dict object to use, or any of those things). Considering you're already subclassing these things, the extensibility cooperation would give would be a great feature.

---

Useful resources: 

* [Raymond Hettinger - Python's super() considered super!][hettinger]
* [Trey Hunter - The problem with inheriting from dict and list in Python][hunter]

[hettinger]: https://rhettinger.wordpress.com/2011/05/26/super-considered-super/ 
[hunter]: https://treyhunner.com/2019/04/why-you-shouldnt-inherit-from-list-and-dict-in-python/

**Comment by grantjenks** [comment]
Indeed, co-operative inheritance does not work. Between the key func and missing func, I think it would be tricky to support. But I’m open to a pull request if there’s a clever solution.

Typically though I just use __missing__ which should work just like dict
