### ISSUE TITLE
Feature Request: SortedDict obtain position for a given key

### ISSUE THREAD

**Issue by vivekfantain** [grantjenks/python-sortedcontainers#135]
Can we have a feature to obtain the position of a key in a sorteddict?  for example sd.position(key) should return 1 through N of the key's position in the Dict.

**Comment by grantjenks** [comment]
Use the index() method: http://www.grantjenks.com/docs/sortedcontainers/sorteddict.html

**Comment by vivekfantain** [comment]
wow how did I miss that.  Thanks
