### ISSUE TITLE
SortedDict does not raise an exception

### ISSUE THREAD

**Issue by Prometheus3375** [grantjenks/python-sortedcontainers#141]
Ordinary dict raises an exception if its size is changed while iterating through it.
```
d = {1: 0, 2: 0, 3: 0, 4: 0}
for k, v in d.items():
    if v == 0:
        del d[k]
print(d)
```
Output
```
Traceback (most recent call last):
  File "sandbox.py", line 10, in <module>
    for k, v in d.items():
RuntimeError: dictionary changed size during iteration
```

Sorted dict runs OK.
```
d = SortedDict({1: 0, 2: 0, 3: 0, 4: 0})
for k, v in d.items():
    if v == 0:
        del d[k]
print(d)
```
Output
```
SortedDict({2: 0, 4: 0})
```

**Comment by grantjenks** [comment]
Per the docs at http://www.grantjenks.com/docs/sortedcontainers/sorteddict.html#sortedcontainers.SortedDict.__iter__

“”” Iterating the sorted dict while adding or deleting items **may** raise a RuntimeError or fail to iterate over all keys.“””

The behavior is documented and by design. But I’m happy to hear more about the use case.

**Comment by Prometheus3375** [comment]
I made such a class. It is like built-in Counter, but with sorted keys and with more convenient for my purposes math operations (they are not listed here).
```python
class Counter(SortedDict):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for k, v in self.items():
            self[k] = v

    def __delitem__(self, key):
        if key in self._dict:
            del self._dict[key]

    def __setitem__(self, key, value):
        if value == 0:
            self.__delitem__(key)
        else:
            self._dict[key] = value
```
This is an erroneous code. `__init__` calls `__setitem__` which deletes keys with value 0. I. e. dict size changes while iterating thought its items. And I used this wrong implementation for a long time. If Counter was a descendant of `dict` class it would raise an exception, I would quickly find this error. But it was a descendant of SortedDict which may not raise it (SortedDict definitely does not raises it since iteration is made in sorted manner), thus I found it much later.

Of course, it is only my fault that I forgot about such behavior of `dict` and did not read documentation for `SortedDict` properly. Since it is documented, I do not think what you need to "fix" my issue.

The fix to my problem is simple:
```python
class Counter(SortedDict):
    def _keys(self): return super().keys()
    def _values(self): return super().values()
    def _items(self): return super().items()

    def keys(self): return tuple(self._keys())
    def values(self): return tuple(self._values())
    def items(self): return tuple(self._items())

    def __iter__(self):
        for k in tuple(super().__iter__()): yield k

    def __reversed__(self):
        for k in tuple(super().__reversed__()): yield k
```
Methods with `_` will be used internally where it is safe. Another solution - created special views for keys/values/items for such data structure.
