### ISSUE TITLE
Index method doesn't work if SortedList elements are instances of a class

### ISSUE THREAD

**Issue by AndyW118** [grantjenks/python-sortedcontainers#142]
I'm (successfully) adding instances of a class to a SortedList, using a key-function which returns an attribute of the class.  But if I try to use Index to locate one of the items in the list, it doesn't find it.  What am I doing wrong?

Thanks
Andy
[SortedListProblem.zip](https://github.com/grantjenks/python-sortedcontainers/files/4303904/SortedListProblem.zip)

**Comment by grantjenks** [comment]
Try reading http://www.grantjenks.com/docs/sortedcontainers/introduction.html#caveats

**Comment by AndyW118** [comment]
Thanks.  Assuming I change the code so it obeys the caveats, how is it then possible to use the index method?  Would its "value" argument be a string or an Element or what?

**Comment by grantjenks** [comment]
SortedKeyList adds a few special key methods: http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedcontainers.SortedKeyList but index_key is not one of them. You would pass an Element.

For fast lookups by key, use a dictionary.

**Comment by AndyW118** [comment]
Thanks once again.
