### ISSUE TITLE
Can we make this persistent?

### ISSUE THREAD

**Issue by kingZthefirst-cypher** [grantjenks/python-sortedcontainers#143]
Hi

I really liked the idea of using little chunks of python lists to store items in a sorted order, and using another python list for storing the maxes, it's a good use of indirection. It also helps in fewer cache misses, as we are just using regular arrays (great locality of reference). I was wondering can we make this persistent (immutable and functional) by using pyrsistent's pvector?

**Comment by kingZthefirst-cypher** [comment]
Hi

I really liked the idea of using little chunks of python lists to store items in a sorted order, and use another python list for storing the maxes, it's a good use of indirection. It also helps in less cache misses, as we are just using regular arrays (good locality of reference). I was wondering can we make this persistent (immutable and functional) by using pyrsistent's pvector?

**Comment by grantjenks** [comment]
First impression: sounds like an interesting experiment. But the API would be so different that it’s probably a different project. Also when I tried pyrsistent several years ago it was quite a bit slower than Python’s built-in lists.

**Comment by kingZthefirst-cypher** [comment]
Thx for the reply. Recently, I really got into functional data structures and functional programming in general. Few days ago I was working on a functional van-emde-boas tree (basically used pmap for the clusters instead of a dictionary). It didn't performed well as expected, but it helped me to understand why functional data structures are so interesting and useful.
