### ISSUE TITLE
Deprecation warning during testing

### ISSUE THREAD

**Issue by scottfurry** [grantjenks/python-sortedcontainers#144]
System - Funtoo (gentoo derivative) x86_64
python: 3.7.6
pytest: 4.5.0
flaky: 3.4.3
sortedcontainers: 2.1.0

While upgrading packaging chain, the deprecation warning below was produced on the command line during package building/testing. Submitting bug report for awareness.
```
======================================================================= warnings summary =======================================================================
tests/test_coverage_sorteddict.py::test_iloc
  /var/tmp/portage/dev-python/sortedcontainers-2.1.0/work/python-sortedcontainers-2.1.0/tests/test_coverage_sorteddict.py:318: DeprecationWarning: sorted_dict.iloc is deprecated. Use SortedDict.keys() instead.
    assert len(temp.iloc) == 26

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===Flaky Test Report===


===End Flaky Test Report===
=========================================================== 359 passed, 1 warnings in 29.93 seconds ============================================================
```

**Comment by grantjenks** [comment]
Sorted Containers library is emitting the deprecation warning. No bug here. I believe you want to open a bug in the application that uses the library.

**Comment by grantjenks** [comment]
Oops, I see you’re running the tests. That deprecation is expected since its testing the deprecated feature.

**Comment by scottfurry** [comment]
Okay. So the deprecation warning is "expected". Good to know.
I wasn't sure if this was important but thought it was important to raise the issue.
Is there a pytest feature for "deprecation" warning?
Otherwise, other google searches should end up here.
Thanks for getting back to me.
