### ISSUE TITLE
Is SortedDict's values sorted as its corresponding key?

### ISSUE THREAD

**Issue by whfuyn** [grantjenks/python-sortedcontainers#153]
Hi, I am currently using SortedDict. I would like to get the values of a span of keys. After bisecting the begin and end of the keys' range, I got the begin and end indices. Is it correct to get the corresponding values by `sorted_dict.values()[begin : end]` ?

**Comment by grantjenks** [comment]
That will work but SortedDict.irange() is likely faster: (sd[key] for key in sd.irange(begin, end))

Note that irange is inclusive of the begin/end by default but you can change that.
