### ISSUE TITLE
SortedSet no longer valid basis for Series or DataFrame in Pandas >= 1.1 

### ISSUE THREAD

**Issue by venaturum** [grantjenks/python-sortedcontainers#156]
With pandas<1.1 the following works

```
import pandas as pd
from sortedcontainers import SortedSet

pd.Series(SortedSet([1,3,2]))
```

but with pandas>=1.1 the following error is raised

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-11-cb88d4b13694> in <module>
> ----> 1 pd.Series(SortedSet([1,3,2]))
> 
> c:\python\python37\lib\site-packages\pandas\core\series.py in __init__(self, data, index, dtype, name, copy, fastpath)
>     325                     data = data.copy()
>     326             else:
> --> 327                 data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
>     328 
>     329                 data = SingleBlockManager.from_array(data, index)
> 
> c:\python\python37\lib\site-packages\pandas\core\construction.py in sanitize_array(data, index, dtype, copy, raise_cast_failure)
>     450         subarr = _try_cast(arr, dtype, copy, raise_cast_failure)
>     451     elif isinstance(data, abc.Set):
> --> 452         raise TypeError("Set type is unordered")
>     453     elif lib.is_scalar(data) and index is not None and dtype is not None:
>     454         data = maybe_cast_to_datetime(data, dtype)
> 
> TypeError: Set type is unordered

However this seems to be a problem even with sets.  eg pd.Series(set([1,3,2])) will also raise the same error.

If using pd.DataFrame instead of pd.Series the following error is raised:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-14-8695fae26fc8> in <module>
> ----> 1 pd.DataFrame(SortedSet([1,3,2]))
> 
> c:\python\python37\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
>     520                     mgr = arrays_to_mgr(arrays, columns, index, columns, dtype=dtype)
>     521                 else:
> --> 522                     mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
>     523             else:
>     524                 mgr = init_dict({}, index, columns, dtype=dtype)
> 
> c:\python\python37\lib\site-packages\pandas\core\internals\construction.py in init_ndarray(values, index, columns, dtype, copy)
>     188     # by definition an array here
>     189     # the dtypes will be coerced to a single dtype
> --> 190     values = _prep_ndarray(values, copy=copy)
>     191 
>     192     if dtype is not None:
> 
> c:\python\python37\lib\site-packages\pandas\core\internals\construction.py in _prep_ndarray(values, copy)
>     319             values = values.copy()
>     320 
> --> 321     if values.ndim == 1:
>     322         values = values.reshape((values.shape[0], 1))
>     323     elif values.ndim != 2:
> 
> AttributeError: 'SortedSet' object has no attribute 'ndim'

However using the standard set works, i.e. pd.DataFrame(set([1,3,2])) does not raise an error.

The reason (not root cause) that SortedSet and set are treated differently with pd.DataFrame is line 501 in pandas.core.frame:

`if not isinstance(data, (abc.Sequence, ExtensionArray)): `

SortedSet is an instance of abc.Sequence whereas set is not.

**Comment by grantjenks** [comment]
This seems like a better issue to raise with the Pandas project. Nothing has changed with sortedcontainers.

Simple workaround is to convert the SortedSet to a list before creating the series: `pd.Series(list(sorted_set))`

**Comment by venaturum** [comment]
Agreed, thanks Grant!
