### ISSUE TITLE
The performance of add method could be improved

### ISSUE THREAD

**Issue by qqwqert007** [grantjenks/python-sortedcontainers#162]
`SortedList.add()` uses `insort(_lists[pos], value)` to insert `value` to `_lists[pos]`. If we replace this line with
```
p = bisect_right(_lists[pos], value)
_lists[pos][p:p] = [value]
```
we can get significant performance improvement. I test with 5 million random int and the improved version is at least 10% faster.

**Comment by grantjenks** [comment]
Please share the benchmark code. The result is surprising.

**Comment by qqwqert007** [comment]
`insort` uses builtin `insert` method to insert a value `a` into an index `p`, but if we use `l[p:p] = [a]` to do the same thing we can make it faster. I did a simple test with 5000, 10000, 15000 and 20000 random numbers to compare the two implementations. It turns out that the `improved_insort` will be much faster when there are more numbers. So maybe we can use this trick to make `SortedList.add()` faster?

```python
from time import time
from bisect import bisect_right, insort
from random import shuffle

def improved_insort(l, a):
    p = bisect_right(l, a)
    l[p:p] = [a]

def insert_arr(arr, insort_func):
    l = []
    for a in arr:
        insort_func(l, a)

for n in [5000, 10000, 15000, 20000]:
    arr = list(range(n))
    shuffle(arr)

    start = time()
    insert_arr(arr, insort)
    original_time = time() - start

    start = time()
    insert_arr(arr, improved_insort)
    improved_time = time() - start

    print("original_time: %.4f  improved_time: %.4f  ratio: %.4f" % (original_time, improved_time, improved_time/original_time))

# original_time: 0.0043  improved_time: 0.0038  ratio: 0.8899
# original_time: 0.0123  improved_time: 0.0083  ratio: 0.6758
# original_time: 0.0209  improved_time: 0.0132  ratio: 0.6291
# original_time: 0.0355  improved_time: 0.0210  ratio: 0.5907
```

**Comment by qqwqert007** [comment]
After more testing, this trick doesn't help with small list. As the `DEFAULT_LOAD_FACTOR` of `SortedList` is 1000, the performance of `add` method cannot be improved.

**Comment by grantjenks** [comment]
I'm surprised `l[p:p] = [a]` is faster than `list.insert`. The former has to construct a list to do the insertion while the latter is simply a function call. Given the significant speedups, two questions:
1. Have you looked through the CPython sources to understand why list.insert or bisect.insort is slower? Seems like there could be a bug worth reporting.
2. Do you have a custom build of Cython or an unusual processor?
