### ISSUE TITLE
Time Complexity of SortedDict

### ISSUE THREAD

**Issue by anuraggupta29** [grantjenks/python-sortedcontainers#164]
Is the time complexity of sd.peekitem(0) or sd.peekitem(-1) also log(n) ?

**Comment by grantjenks** [comment]
Yes. Per the docs at http://www.grantjenks.com/docs/sortedcontainers/sorteddict.html#sortedcontainers.SortedDict.peekitem the runtime is O(log(n)) in the general case of any index.

In the specific case of index 0 or -1, the runtime is O(1). There exists a fast-path for those special cases.
