### ISSUE TITLE
One file library.

### ISSUE THREAD

**Issue by bastiat** [grantjenks/python-sortedcontainers#165]
Thank you for nice library.
Is sortedcontainers library available as a one file - to include by simple copy-paste, not by a pip? 
- I would like to use it in an environment, where I can't use pip. 

My case for it is I need it for programming contest where I'm allowed to only post one python file, containing both my code, and all available libraries included.

Do you consider releasing it also in such form - as a one file library? If not why? Would it be hard and complex, or do you find it useless? (I'm PSL).

Regards.

**Comment by grantjenks** [comment]
It’s not available as a single file.

There’s one file for each of the core data types: sorted list, sorted set, and sorted dict. You can try concatenating those files and fixing up the imports.

Otherwise, seems like a big single file would be a challenge for maintainability.

**Comment by bastiat** [comment]
Thx for response and clarification.
