### ISSUE TITLE
Wrong graphs.

### ISSUE THREAD

**Issue by bastiat** [grantjenks/python-sortedcontainers#166]
Thank you for nice library.

 It seems to me that graphs at http://www.grantjenks.com/docs/sortedcontainers/performance.html#id2 are wrong. 

It seems to me that all of them show linear complexity which is wrong in most cases. Eg SortedDict.__contains__() shows linear time complexity which is true for skip-list, but wrong for AVL-tree, B-tree, RB-tree - contains has O(log(N)) time for them.

Please clarify if the graphs are mistaken or I'm somehow wrong with them?

Regards

**Comment by grantjenks** [comment]
For each operation, the benchmark code repeats it over 1% of the source size. So for 1,000 elements, the contains operation is repeated 10 times and at 1,000,000 elements, the operation is repeated 10,000 times. So in the benchmarks there’s a linear term like “n*(op time)” on display. For many of the operations, the linear term dominates.

Specifically for sorted dict, the contains operation is O(1) so linear is expected.

Also the axes are log-log which further flattens the big-o effects. And this is fundamental to the premise of sorted containers: for memory-contained workloads, “n” just doesn’t get big enough. Read http://www.grantjenks.com/docs/sortedcontainers/performance-scale.html for more.

Per the documentation, the sources are in the tests directory in files prefixed with “benchmark”. Please take a look.
