### ISSUE TITLE
How to copy, view, deleted all elements of a sortedDict with keys smaller than a certain k

### ISSUE THREAD

**Issue by yguel** [grantjenks/python-sortedcontainers#168]
Everything is in the title. I would like to perform those operations as fast as possible.
Retrieving or making a shallow copy of the binary subtree would be perfect (if SortedDict is implemented as a binary tree) such as I expect methods to do that. So far I did not find them.

Is it a present functionality and I miss it in the doc (which is realy great by the way) or do I have to get all the keys and perform the operations key by key ?

**Comment by grantjenks** [comment]
Sorted containers doesn’t use a binary tree internally. But there is an API called “irange” that can help with queries like yours: http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedcontainers.SortedList.irange The irange method is also present on SortedDict and yields the keys.

**Comment by yguel** [comment]
Thanks for the answer. That is very interesting, do you know how it compared with binary trees ?

**Comment by grantjenks** [comment]
Here’s an example:
```
import sortedcontainers as sc

d1 = sc.SortedDict(enumerate(range(10)))
print(d1)
d2 = sc.SortedDict((k, d1[k]) for k in d1.irange(maximum=4))
print(d2)
```

**Comment by grantjenks** [comment]
Performance is discussed at length in the docs: http://www.grantjenks.com/docs/sortedcontainers/performance.html

**Comment by yguel** [comment]
Whouahh, great !
