### ISSUE TITLE
SortedDict |= incorrect behavior

### ISSUE THREAD

**Issue by bulaiden** [grantjenks/python-sortedcontainers#169]
SortedDict implementation of |= (augmented assignment union operator) is currently incorrect.
For d1 |= d2, it will not add keys of d2 that are missing in d1.

In comparison, the regular union operator d1 | d2 works fine.

**Comment by grantjenks** [comment]
Oops, yes, that’s a bug. The code is currently using “|=“ inherited from dict which means the internal indexes aren’t updated.

I think “|=“ is similar to “update” which may be a workaround until this is fixed.

**Comment by grantjenks** [comment]
In PEP 584, there’s a good reference implementation based on update(): https://www.python.org/dev/peps/pep-0584/#reference-implementation . That code would likely work for SortedDict with appropriate tests added.

**Comment by grantjenks** [comment]
Released in 2.4.0 to PyPI
