### ISSUE TITLE
"lower_bound()" function same as that of C++ STL's "map" library

### ISSUE THREAD

**Issue by NabeelQaiser** [grantjenks/python-sortedcontainers#172]
Hi,

Firstly, thank you for this library in python.

One key functionality I am requiring in my work is to get the "lower bound" of a key, i.e., (say "ordered_dict_name" is an instance of "SortedDict" class) ordered_dict_name.lower_bound(k) should return the (key, value) tuple present against the given key 'k', and if that 'k' isn't present, then return the (key, value) tuple present against the key just greater than 'k'.

more clarification: https://www.geeksforgeeks.org/map-lower_bound-function-in-c-stl/

**Comment by grantjenks** [comment]
Use SortedDict.irange http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedcontainers.SortedList.irange I think that’s the closest provided API.

**Comment by NabeelQaiser** [comment]
> Use SortedDict.irange http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedcontainers.SortedList.irange I think that’s the closest provided API.

Thanks! this works.
