### ISSUE TITLE
SortedSet: Are changing comparison keys allowed if they maintain their relative position?

### ISSUE THREAD

**Issue by Daniel-Abrecht** [grantjenks/python-sortedcontainers#174]
I would like to do something like this:
```
self.parsejobs = SortedSet(key=lambda job: (job.min - self.offset) & 0xFFFFFFFF)
```
`job.min` is constant, but `self.offset` isn't. Both are numbers in the modulo space 0 to 2^32. I only ever increase `self.offset`, and I make sure to remove all elements from the set where `((job.min - self.offset) & 0xFFFFFFFF) < ((new_offset - self.offset) & 0xFFFFFFFF)` before I update the offset `self.offset = new_offset`.

Therefore, the order of elements in this set never changes, and the differences of the values returned by the key function for all elements never changes, but the value returned by the key function does change.

I would like to know if `SortedSet` can be used like this or not. The documentation doesn't seam to mention if the comparison key needs to be constant, or if it is enough if it's relative position is maintained.

**Comment by grantjenks** [comment]
It’s in the Introduction > Caveats > (2) at http://www.grantjenks.com/docs/sortedcontainers/introduction.html#caveats

The key must not change.
