### ISSUE TITLE
Sometimes SortedList.index throws ValueError when item is in list?

### ISSUE THREAD

**Issue by patrickkidd** [grantjenks/python-sortedcontainers#175]
I have a type with `__lt__` implemented that sorts well but `SortedList.index` and `SortedList.__contains__` indicate that an item of this type doesn't exist in the list while it clearly does exist in the list. I realize a reproducible example would be ideal here, but since this is a custom type I thought I would check first for any known conditions that may cause this to occur.

Thanks!

**Comment by grantjenks** [comment]
Check caveats first: http://www.grantjenks.com/docs/sortedcontainers/introduction.html#caveats

**Comment by patrickkidd** [comment]
This is a great part of the docs! Bravo. It already pointed out two problems in my type. I'll test and see if they fix the problem in this particular case.
