### ISSUE TITLE
Need Help For Competative Programming

### ISSUE THREAD

**Issue by UdayKiranPadhy** [grantjenks/python-sortedcontainers#176]
Hi and Hello There, I liked you library sortedcontainers, works amazing. Being a Competative programmer , i am unable to use your library in online editors as we cannot import libraries other than those which comes with Python pre installed , is there any piece of code by which i could just copy that class and make an instance of it and use it ?. I just want to use SortedList, I looked into the code and found that there were too many lines and even couldnot undertand which all to copy . Is there any way to get ur SortedList instance without installing ??

**Comment by grantjenks** [comment]
The class is in sortedlist.py but is several hundred lines of code.
