### ISSUE TITLE
What's the underlying Data Structure or Algorithm of these implementation?

### ISSUE THREAD

**Issue by idontknoooo** [grantjenks/python-sortedcontainers#177]
Hi,

I am trying to learn these code and their implementations. For `TreeMap` in Java, it's based on `Red-Black Tree`, I was wondering if `SortedDict` using a similar design or there is something else?

Thank you in advance.

**Comment by grantjenks** [comment]
From the docs:
- http://www.grantjenks.com/docs/sortedcontainers/implementation.html
- http://www.grantjenks.com/docs/sortedcontainers/performance-scale.html

**Comment by idontknoooo** [comment]
Sorry for the late reply. Thank you very much!
