### ISSUE TITLE
feat: return index where item is added when calling SortedList.add()

### ISSUE THREAD

**Issue by MarrickLip** [grantjenks/python-sortedcontainers#195]
Hi,

For a use case I'm working with at the moment ([today's LeetCode.com challenge](https://leetcode.com/problems/count-of-smaller-numbers-after-self/) 🤓) it is necessary to know the index at which an item gets inserted to after calling `s.add(item)`, where `s` is a `SortedList`.

However, the `add` method returns nothing and so I have to call `s.bisect_left(item)` to get the index and then `s.add(item)` to perform the update. This is a waste of computation, however.

Currently `s.add(item)` returns nothing so it would be a backwards compatible change to return the index where the item is added. I had a look at `sortedlist.py` and it appears that this would be a fairly straight forward feature to implement, but I couldn't go about it myself as I can't wrap my head around a few edge cases e.g. how best to handle when the inserted item already exists and hence the index it enters is arbitrary. 

Thanks,

Marrick.

**Comment by grantjenks** [comment]
Getting the index of the item requires the positional index to be built which add() specifically avoids. I think this is a fine example for simply inheriting and implementing the needed functionality in your own code.

The other problem is that bisect.insort doesn’t return the index and that’s what’s used by the library. Get that changed in Python and the project could benefit.

**Comment by MarrickLip** [comment]
Gotcha! Thanks for looking into it though :D

**Comment by Serpens66** [comment]
> Gotcha! Thanks for looking into it though :D

I just asked the same question (sorry for not searching properly).
Did you MarrickLip implement your own function that does this and is still faster than doing both operations one after the other?
