### ISSUE TITLE
Add `get(key[, default])` method

### ISSUE THREAD

**Issue by cjwcommuny** [grantjenks/python-sortedcontainers#197]
Add the `get(key[, default])` method for sorted container like `dict` in Python.

Here is the doc copied from Python standard library:

```python
get(key[, default])
```

Return the value for key if key is in the dictionary, else default. If default is not given, it defaults to None, so that this method never raises a [KeyError].

**Comment by grantjenks** [comment]
It’s there already.

**Comment by cjwcommuny** [comment]
`SortedDict` has already implemented `get(key[, default])`. But can we add this method to `SortedSet`?

**Comment by grantjenks** [comment]
Sets don’t typically work that way in Python.

Use inheritance to extend the data types as needed.
