### ISSUE TITLE
SortedList.add complexity: O(log(n)) or O(n)?

### ISSUE THREAD

**Issue by Dmitrii-I** [grantjenks/python-sortedcontainers#202]
The docs claim complexity of O(log(n)), approximately. Looking at the source of [SortedList.add](https://grantjenks.com/docs/sortedcontainers/_modules/sortedcontainers/sortedlist.html#SortedList.add) I see that most frequently run branch uses [bisect.insort](https://docs.python.org/3/library/bisect.html#bisect.insort) which has complexity of O(n). 

Wouldn't it be better to say the complexity is approximately O(n)?

**Comment by Dmitrii-I** [comment]
OK, I found an answer by the author: https://stackoverflow.com/questions/63430867/time-complexity-of-operations-in-sortedlist-python

Closing issue.

**Comment by grantjenks** [comment]
See https://grantjenks.com/docs/sortedcontainers/performance-scale.html for a detailed discussion of the runtime complexity.

**Comment by Dmitrii-I** [comment]
Yup, saw it, thanks. Also did a small test:


```
import random
import time


def print_time(list_size):
    sorted_list = SortedList([random.randint(1, 777) for _ in range(list_size)])
    times = []
    for _ in range(777):
        tmp = sorted_list.copy()
        random_value = random.randint(1, 777)
        start = time.perf_counter()
        tmp.add(random_value)
        end = time.perf_counter()
        times.append(end - start)

    print(min(times))


if __name__ == "__main__":
    print_time(list_size=1000)
    print_time(list_size=10000)
    print_time(list_size=100000)
    print_time(list_size=1000000)
```

And got these times:

```
1.0310031939297915e-06
1.334003172814846e-06
1.487991539761424e-06
1.0108982678502798e-05
```

So while input increases by factor of ten the times do not. Last one is meh. I probably did something wrong.
