### ISSUE TITLE
Feature request: SortedDict irange_values()

### ISSUE THREAD

**Issue by GijsGroote** [grantjenks/python-sortedcontainers#211]
Currently if i want to select the values from a range in a SortedDict, for example I want range 0.5 to 2.5 from `sd`:
`sd = SortedDict({0: "zero", 1: "one", 2: "two", 3: "three"})`

Thus I then want back `{"one", "two"}`

Could be done with:
```
result = set()
for key in sd.irange(0.5, 2.5):
   result.add(sd[key])
```

This scales not all that great, O(n*log(n)) I think.

Could I directly get the values from the SortedDict with O(log(n)) computation time?

**Comment by grantjenks** [comment]
The “sd[k]” operation is O(1) not O(log(n)) so it isn’t an issue. The runtime complexity is O(log(n) + k) where n is the number of elements in the container and k is the number of elements in the range.
