### ISSUE TITLE
Feature request: OrderedDict with peekitem

### ISSUE THREAD

**Issue by MischaPanch** [grantjenks/python-sortedcontainers#212]
Hi, thank you for this great library!

I know it is called sortedcontainers and not orderedcontainers, but I wondered whether the following might be a useful addition to this scope: an OrderedDict with the same functions as SortedDict, just not ordered by keys.

I have this use case quite often that I want to extract items from a dict by the "index", which makes sense since in newer versions of python all dicts are ordered. This always requires custom implementation, the naive one of O(n) complexity (python's standard dict or OrderedDict don't offer this functionality). However, I don't need and often don't want the dicts to be sorted in any way, rather I want them to keep the order that I add items to them, so SortedDict doesn't help me there

As far as I can tell, it would be extremely simple to implement - this kind of OrderedDict would be the same as SortedDict, but with the `_list` attribute being a normal list instead of `SortedList`. Then `peekitem` will get O(n) complexity.

If you think this is a useful extension, I would be happy to prepare a PR. Otherwise I will have to copy your implementation of SortedDict to my code and replace the `_list`, which is a shame, since I would much rather simply use your library

**Comment by grantjenks** [comment]
It’s already implemented in a separate library called “sortedcollections” which is based on “sortedcontainers”. See https://grantjenks.com/docs/sortedcollections/ordereddict.html
