### ISSUE TITLE
SortedSet.__contains__ incorrect runtime complexity?

### ISSUE THREAD

**Issue by stbneb** [grantjenks/python-sortedcontainers#215]
Hi, in the docs it says that [`SortedSet.__contains__`](https://grantjenks.com/docs/sortedcontainers/sortedset.html#sortedcontainers.SortedSet.__contains__) has a runtime complexity of O(1), how so?
From what I understand it is O(1) in the best case and O(n) in the worst case as the `__contains__` method uses the `in` operator on a standard python set which, at least in CPython, its `__contains__` method has the aforementioned time complexities.

If the docs are wrong I can submit a PR to fix it or an explanation on how it was concluded to be O(1) could be added.

**Comment by grantjenks** [comment]
The docs are technically wrong but I don’t think it’s worth going into all that detail in a docstring. To get the O(n) behavior you must write an object whose hash is rather lousy. If you do that then you should know that the guarantees of many containers are void.
