### ISSUE TITLE
sdist is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [grantjenks/python-sortedcontainers#216]
The sdist package at PyPI is missing the `tox.ini` file.  Please add the file to sdist to make downstream testing easier.  Thanks.

**Comment by grantjenks** [comment]
I don't know how to do that but I'm open to a PR.

**Comment by mtelka** [comment]
It looks like you are using `setuptools` as the build backend so simple addition of `include tox.ini` to `MANIFEST.in` should do the trick.  Documentation: https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html

I can create a PR, but I cannot test it reliably, because I do not know how exactly you create sdist, what versions of packages you use, etc.

**Comment by grantjenks** [comment]
I'm gonna change that soon to pyproject.toml. Better hold off until then. Updates coming.

**Comment by mtelka** [comment]
Could you please reopen this issue then?
