### ISSUE TITLE
Different key-functions for sorting and comparing items in SortedSet

### ISSUE THREAD

**Issue by AndreiPashkin** [grantjenks/python-sortedcontainers#220]
I wonder if it's a good idea to make a PR that would implement an option for another key-function for `SortedSet()` that would be used for comparing items (but not for sorting)?

**Comment by grantjenks** [comment]
Are you suggesting a comparator function? Pythons standard library already provides cmp_to_key in the functools module: https://stackoverflow.com/questions/32752739/how-does-the-functools-cmp-to-key-function-work
