### ISSUE TITLE
Improve performance: Switch segment tree to Fenwick Tree

### ISSUE THREAD

**Issue by 981377660LMT** [grantjenks/python-sortedcontainers#221]
I read through the SortedList source code carefully and found that the source code uses a  [segment tree](https://cp-algorithms.com/data_structures/segment_tree.html#sum-queries) to maintain the sum of the list lengths. 
In fact, a  [Fenwick Tree](https://cp-algorithms.com/data_structures/fenwick.html) can be used instead, which can effectively improve the constants.

**Comment by grantjenks** [comment]
Not interested.
