### ISSUE TITLE
Documentation CI status badges are broken

### ISSUE THREAD

**Issue by smith558** [grantjenks/python-sortedcontainers#222]
Web documentation [https://grantjenks.com/docs/sortedcontainers/#features](https://grantjenks.com/docs/sortedcontainers/#features) CI status badges are broken.

![image](https://github.com/grantjenks/python-sortedcontainers/assets/44023416/a248a109-5ddb-47fd-b7d4-9cb9da5d67fe)

**Comment by grantjenks** [comment]
Fixed.
