### ISSUE TITLE
Problem with inheritance from SortedSet 

### ISSUE THREAD

**Issue by puiseux** [grantjenks/python-sortedcontainers#224]
Hello,
I create a `class Index` that inherits from `SortedSet`. But `Union` does not work as expected.
Here is the piece of code :
```
from sortedcontainers import SortedSet

class Index(SortedSet):
    def __init__(self, r:range or list or tuple or np.ndarray):
        super(Index, self).__init__(r)

if __name__=='__main__' :
    S = Index([])
    S1 = Index([2,3,0])
    print(S.union(S1))
```
and here is the result :
```
Index([])
Index([0, 2, 3])
Traceback (most recent call last):
  File "/Users/puiseux/GitHub/fonctions-discretes/src/py3/index.py", line 27, in <module>
    print(S.union(S1))
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/sortedcontainers/sortedset.py", line 658, in union
    return self.__class__(chain(iter(self), *iterables), key=self._key)
TypeError: __init__() got an unexpected keyword argument 'key'
```
Notice that if I replace `Index` with `SortedSet`, it works perfectly :
```
SortedSet([])
SortedSet([0, 2, 3])
SortedSet([0, 2, 3])
```

**Comment by puiseux** [comment]
Well, it looks like a bug in sortedset.py : 
`SortedSet.union()` calls `SortedSet.__class__(x,k=self._key)` with **two arguments** instead of **one unique argument** as stated in `object.__class__(x)`  from `builtins.py`
So I just override `SortedSet.union()` (locally) like this :

```
    def union(self, *iterables):
        # return self.__class__(chain(iter(self), *iterables), key=self._key)
        return self.__class__(chain(iter(self), *iterables))
```

With this patch, it looks OK.

**Comment by puiseux** [comment]
Well, a better solution is to declare `Index.__init__(iterable=None, key=None)`  with `**key**` argument.

**Comment by grantjenks** [comment]
The init method of SortedSet adds an optional key parameter. Your subclass version is taking that away which is going to cause issues. See https://stackoverflow.com/questions/6034662/python-method-overriding-does-signature-matter for a description of the issue.
