### ISSUE TITLE
count() missing from SortedDict

### ISSUE THREAD

**Issue by h4l** [grantjenks/python-sortedcontainers#226]
The [SortedDict docs](https://grantjenks.com/docs/sortedcontainers/sorteddict.html) say it has the `count()` method from SortedList, but it's not actually added when other list methods are, so doesn't exist at runtime.

https://github.com/grantjenks/python-sortedcontainers/blob/92ef500158f87f7684023823d689cfd7bef892a1/src/sortedcontainers/sorteddict.py#L98C25-L98C28

https://github.com/grantjenks/python-sortedcontainers/blob/92ef500158f87f7684023823d689cfd7bef892a1/src/sortedcontainers/sorteddict.py#L170

**Comment by grantjenks** [comment]
Hmm, What to do here? Count can only be one or zero since they are keys in the dictionary. Doing the bisect with SortedList is probably not desired. The “contains” check will be much faster. I should probably just remove that from the docs. How does that sound?

**Comment by h4l** [comment]
I agree, removing it from the docs sounds like a good solution.

**Comment by grantjenks** [comment]
Fixed in 94e2557
