### ISSUE TITLE
Element not found in SortedList when 3 requirements are not violated

### ISSUE THREAD

**Issue by littleQiu22** [grantjenks/python-sortedcontainers#227]
In [official document](https://grantjenks.com/docs/sortedcontainers/introduction.html#caveats) , an example which satisfies 3 necessary requirements is proposed:
 ```python
class Record(object):
    def __init__(self, name, rank):
        self.name = name
        self.rank = rank
    def __lt__(self, other):
        return self.rank < other.rank
```
Following official usage works well:
```python
alice1 = Record('alice', 1)
bob2 = Record('bob', 2)
carol3 = Record('carol', 3)
bob4 = Record('bob', 4)
bob2 != bob4  # <-- Different instances, so unequal. GOOD!
True
sl = SortedList([alice1, bob2, carol3, bob4])
bob2 in sl
True
bob4 in sl
True
```
But when two elements with the same key are defined below, then element cannot be found:
```python
alice = Record('alice', 1)
bob = Record('bob', 1)
sl = SortedList([alice, bob])
bob in sl
False # should be True
```

**Comment by grantjenks** [comment]
Think carefully about the last example. How should the list order alice and bob? alice < bob is false and bob < alice is false and alice == bob is false. That is not a total ordering.
