### ISSUE TITLE
right pattern for get-or-add in sortedset/list/dict

### ISSUE THREAD

**Issue by BrannonKing** [grantjenks/python-sortedcontainers#228]
I'm looking for an efficient way to do this
```python
state = my_sorted_set.get_or_add(new_state)
```
where state then equals the old state object if an instance of it was already in the set. Otherwise it would equal new_state, which is now also in the set.

Similar method in C#: https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutableinterlocked.getoradd?view=net-7.0

**Comment by grantjenks** [comment]
https://grantjenks.com/docs/sortedcontainers/sorteddict.html#sortedcontainers.SortedDict.setdefault
