### ISSUE TITLE
[Question] Better way to pick the N smallest values in SortedList

### ISSUE THREAD

**Issue by felipeinagaki** [grantjenks/python-sortedcontainers#230]
Hi,  thank you for the valuable lib
Suppose that I have M>N values on a SortedList and I want to pick the N smallest ones. What is the better way to do that? 

I'm doing  `my_list = SortedList(my_list[:N])`, but probably it is not the best approach.

Thanks in advance

**Comment by grantjenks** [comment]
That's the correct way to do that.
