### ISSUE TITLE
Update OS packages

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/python-sortedcontainers#37]
@sandrotosi Could you upgrade the Debian packages? I just released version 1.4.2. If you want the docs and all, you'll have to pull it from the git repo at tag v1.4.2.

Thank you.

**Comment by grantjenks** [comment]
@sandrotosi Could you upgrade the Debian packages? I just released version 1.4.4. If you want the docs and all, you'll have to pull it from the git repo at tag v1.4.4.

Thank you.

**Comment by sandrotosi** [comment]
Just pushed 1.4.4 to debian unstable; it will take a bit of time to reach it "for real" as I introduced a new package (for the documentation) and that needs to be processed manually

**Comment by grantjenks** [comment]
@sandrotosi Thank you so much!

Fyi, just pushed v1.5.2 to PyPI. Most significant source change is a new ``SortedDict.peekitem(index=-1)`` method that others may want/need. I also made numerous docs and linting improvements.

If I can help with the Debian updates, please let me know.

**Comment by sandrotosi** [comment]
hey @grantjenks sorry for the delay, I just pushed sorted_containers v1.5.3 to debian

**Comment by grantjenks** [comment]
Thanks!

**Comment by grantjenks** [comment]
Hi @sandrotosi. I recently made a significant update to Sorted Containers.

The source, docs, and tests are downloadable at https://github.com/grantjenks/python-sortedcontainers/archive/v2.0.3.zip

You can read about the changes at http://www.grantjenks.com/docs/sortedcontainers/history.html

Thank you for updating the Debian package.

**Comment by sandrotosi** [comment]
@grantjenks i've just uploaded 2.0.4 to our development branch - thanks!
