### ISSUE TITLE
Submit to JOSS (Journal of Open Source Software)

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/python-sortedcontainers#71]
I've had a request for citation in a paper. Matthias Bussonnier (of IPython/Jupyter) was kind enough to point me to the Journal of Open Source Software (JOSS) at PyBay. Seems worth it.

http://joss.theoj.org/

**Comment by grantjenks** [comment]
Note that SymPy used PeerJ which may be a good alternative: https://peerj.com/computer-science/

**Comment by grantjenks** [comment]
Submitted: https://joss.theoj.org/papers/e8b71872eaf49e7dead39eefee7c5a21 Waiting now for review.

**Comment by amirouche** [comment]
Thanks! I am using your project in https://github.com/amirouche/hoply/ I think I also apply to joss.
