### ISSUE TITLE
What is the reason for ValueError not in list?

### ISSUE THREAD

**Issue by kpagcha** [grantjenks/python-sortedcontainers#96]
I am using a `SortedSet` of objects that define `__lt__`. The type of the attributes getting compared is `datetime.datetime`, adn I am making sure we never have a `None` value in the set. I am constantly adding and discarding just fine, but for some reason I cannot pinpoint, at some point I get the error

`ValueError: <object> not in list`

when trying to discard an object that DOES exist (according to the membership `in` operator).

The objects' attribute by which we sort is mutable, but I've tested this and `SortedSet` seems to be able to handle it. Also, objects with the same attribute value may and will exist in the set.

This error is driving me absolutely crazy. Does it hint at anything else that may be going wrong with my data? Or is it an actual bug?

**Comment by grantjenks** [comment]
Hi there -- I see you open/closed the issue so I hope you found the problem. I wonder if there are any specific docs that would've been helpful in this case. I tried to cover some of the scenarios in Caveats on the Introduction page: http://www.grantjenks.com/docs/sortedcontainers/introduction.html#caveats Did you find that? Was it useful?
