### ISSUE TITLE
Bug sorteddict no method iteritems

### ISSUE THREAD

**Issue by valour01** [grantjenks/python-sortedcontainers#97]
It seems that the version 2.0.4 has a bug that the sorteddict has no method iteritems and will treat it as the property. I guess it is caused by the following code

```
        iteritems = __make_raise_attributeerror('iteritems', 'items')
```

in the line 375, file sortedict.py. You can verify. Many Thanks

**Comment by grantjenks** [comment]
That’s intentional. V2 embraced the semantics of Python 3 which removed “iteritems” in favor of just “items”. See the release notes for more information: http://www.grantjenks.com/docs/sortedcontainers/history.html#v2
